[project]
name = "flask-eventlet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "eventlet>=0.40.3",
    "flask>=3.1.2",
]
